package team1793.menu;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import team1793.HourLogger;
import team1793.dialog.CameraLogin;
import team1793.dialog.LoginMember;

import javax.swing.*;
import java.awt.*;

/**
 * Created by tyler on 10/8/16.
 */
public class MainMenu implements IMenu {
    private JButton loginButton;
    private JPanel rootPanel;
    private JButton viewMembersButton;
    private JButton cameraButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public MainMenu() {
        viewMembersButton.addActionListener(e -> HourLogger.setMenu(new ViewMembers()));
        loginButton.addActionListener(e -> new LoginMember());
        cameraButton.addActionListener(e -> new CameraLogin());
    }

    @Override
    public Container getContentPane() {
        return rootPanel;
    }

    @Override
    public void update() {

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setBackground(new Color(-12828863));
        rootPanel.setEnabled(true);
        rootPanel.setOpaque(true);
        cameraButton = new JButton();
        cameraButton.setText("QR Login/Logout");
        rootPanel.add(cameraButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loginButton = new JButton();
        loginButton.setText("Manual Login/Logout");
        rootPanel.add(loginButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        viewMembersButton = new JButton();
        viewMembersButton.setEnabled(true);
        viewMembersButton.setText("View Members");
        rootPanel.add(viewMembersButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
